### ANALYTIC REPOSITORY
# All analytics below will be loaded into the program for the
# user to interact with. Please ensure that analytics follow
# the base template provided below.

# {{ example analytic }}
# Analytic Name:
#   abbr: AN
#   description: Short, sufficient description of analytic.
#   extension:
#     - list
#     - of
#     - acceptable
#     - file
#     - extensions


tableau_shell: &tableau_shell
  name: "[Client Name] - [Analytic Name] - [Plan Name] - FY[XX]"
  description: Details changes between the provided populations.
  
memo_pkg: &memo_pkg
  - Combined Scoping and Summary Memo
  - Procedures Memo
  - Controls Over Audit Tools Memo
  
outputs_pkg: &outputs_pkg
  tableau_shell: *tableau_shell
  memos: *memo_pkg


Demographic Data Analytic:
  path: DDA
  description: |
    The Demographic Data Analytic is a year-over-year comparison of demographic populations.
    Changes are recorded and highlighted for audit teams to assess a demographic population
    has not significantly changed between periods (typicall consecutive years).
    
    This analytic makes use of PII data - please see the PII tab to learn more about how to
    safely handle the data required for this analytic.
  datasets:
    - Data Request Form
    - Prior Period Census
    - Current Period Census
  <<: *outputs_pkg


401k Compliant Analytic:
  path: 401(k)
  description: |
    The 401(k) Compliant Analytic is a year-over-year comparison of demographic populations.
    Changes are recorded and highlighted for audit teams to assess a demographic population
    has not significantly changed between periods (typicall consecutive years).
    
    This analytic makes use of PII data - please see the PII tab to learn more about how to
    safely handle the data required for this analytic.
  datasets:
    - Data Request Form
    - 401k Data
  <<: *outputs_pkg


PITA Valuation:
  path: PITA/Valuation Module
  description: |
    The Valuation Module is a year-over-year comparison of demographic populations.
    Changes are recorded and highlighted for audit teams to assess a demographic population
    has not significantly changed between periods (typicall consecutive years).
    
    This analytic makes use of PII data - please see the PII tab to learn more about how to
    safely handle the data required for this analytic.
  datasets:
    - Data Request Form
    - DNAV Input
  <<: *outputs_pkg


PITA Risk Assessment:
  path: PITA/Risk Assessment Module
  description: |
    The Risk Assessment Module is a year-over-year comparison of demographic populations.
    Changes are recorded and highlighted for audit teams to assess a demographic population
    has not significantly changed between periods (typicall consecutive years).
    
    This analytic makes use of PII data - please see the PII tab to learn more about how to
    safely handle the data required for this analytic.
  datasets:
    - Data Request Form
    - DNAV Input
  <<: *outputs_pkg
