### ANALYTIC REPOSITORY
# All analytics below will be loaded into the program for the
# user to interact with. Please ensure that analytics follow
# the base template provided below.

# {{ example analytic }}
# Analytic Name:
#   abbr: AN
#   description: Short, sufficient description of analytic.
#   extension:
#     - list
#     - of
#     - acceptable
#     - file
#     - extensions




Demographic Data Analytic:
  path: DDA
  description: |
    The Demographic Data Analytic is a year-over-year comparison of demographic populations.
    Changes are recorded and highlighted for audit teams to assess a demographic population
    has not significantly changed between periods (typicall consecutive years).
    
    This analytic makes use of PII data - please see the PII tab to learn more about how to
    safely handle the data required for this analytic.
  inputs:
    - Data Request Form
    - Prior Period Census
    - Current Period Census
  outputs:
    tableau:
      name: [Client Name] - DDA - [Plan Name] - FY[XX]
      description: Details changes between the provided populations.
    memos:
      - Combined Scoping and Summary
      - Procedures
      - Controls Over Audit Tools


401k Compliant Analytic:
  path: 401(k)
  description: Description of analytic
  inputs:
    - Data Request Form
    - 401k Data
  outputs:
    tableau:
      path: something
      description: something
    memos:
      - Combined Scoping and Summary
      - Procedures
      - Controls Over Audit Tools


PITA Valuation:
  path: PITA/Valuation Module
  description: The 401(k) Compliant Analytic is something I do not understand.
  inputs:
    - Data Request Form
    - DNAV Input
  outputs:
    tableau:
      path: unsure
      description: unknown
    memos:
      - Combined Summary and Scoping
      - Procedures
      - Controls Over Audit Tools


PITA Risk Assessment:
  path: PITA/Risk Assessment Module
  description: The 401(k) Compliant Analytic is something I do not understand.
  inputs:
    - Data Request Form
    - DNAV Input
  outputs:
    tableau:
      path: unsure
      description: unknown
    memos:
      - Combined Summary and Scoping
      - Procedures
      - Controls Over Audit Tools
