Data Request Form:
  description: Provide client-level data and field mapping.
  extension: xlsx
  sheets:
    - Input Parameter
    - Mapping Parameter

Census Data:
  description: Census level demographic data from current period.
  extension:
    - csv
    - xlsx
    
DNAV Input:
  description: I actually don't know what this data is.
  extension:
    - csv
    - xlsx
