EBP Shiny:
    path: \\hdcaersnas/AERS/WEST/auditinnovationdata_fpx1140501/EBP - Employee Benefit Plans/FY24 Analytics Shells
    analytics:
        Demographic Data Analytic:
            path: DDA
            description: The Demographic Data Analytic is a year-over-year comparison of demographic populations. Changes are recorded and highlighted for audit teams to assess a demographic population has not significantly changed between periods (typicall consecutive years).
            outputs:
                Tableau:
                    abbr: TWBX
                    description: Pretty cool looking dashboards to describe the data.
                Combined Memo:
                    abbr: 1200E
                    description: Form DA1200E, Data Analytics Specialist Combined Scoping and Summary Memo for Employee Benefit Plan (EBP) Audits.
                Procedures Memo:
                    abbr: PROC
                    description: This memo will populate for you.
                Controls Over Audit Tools Memo:
                    abbr: 22852
                    description: This memo will populate for you.
            inputs:
                Data Request Form:
                    abbr: DRF
                    description: Provide client-level data and field mapping.
                    sheets:
                        - Input Parameter
                        - Mapping Parameter
                Prior Year Census:
                    abbr: PY
                    description: Census level demographic data from prior period.
                Current Year Census:
                    abbr: CY
                    description: Census level demographic data from current period.
        401(k) Compliant Analytic:
            path: 401(k)
            description: The 401(k) Compliant Analytic is something I do not understand.
            outputs:
                Tableau:
                    abbr: TWBX
                    description: Pretty cool looking dashboards to describe the data.
                Combined Memo:
                    abbr: 1200E
                    description: This memo will populate for you.
                Procedures Memo:
                    abbr: PROC
                    description: This memo will populate for you.
                Controls Over Audit Tools Memo:
                    abbr: 22852
                    description: This memo will populate for you.
            inputs:
                Data Request Form:
                    abbr: DRF
                    description: Provide client-level data and field mapping.
                Dataset 2:
                    abbr: D2
                    description: Census level demographic data from prior period.
                Dataset 3:
                    abbr: D3
                    description: Census level demographic data from current period.
        PITA (Risk Assessment):
            path: PITA/Risk Assessment Module
            description: The 401(k) Compliant Analytic is something I do not understand.
            outputs:
                Tableau:
                    abbr: TWBX
                    description: Pretty cool looking dashboards to describe the data.
                Combined Memo:
                    abbr: 1200E
                    description: This memo will populate for you.
                Procedures Memo:
                    abbr: PROC
                    description: This memo will populate for you.
                Controls Over Audit Tools Memo:
                    abbr: 22852
                    description: This memo will populate for you.
            inputs:
                Data Request Form:
                    abbr: DRF
                    description: Provide client-level data and field mapping.
                Dataset 2:
                    abbr: D2
                    description: Census level demographic data from prior period.
                Dataset 3:
                    abbr: D3
                    description: Census level demographic data from current period.
        PITA (Valuation Module):
            path: PITA/Valuation Module
            description: The 401(k) Compliant Analytic is something I do not understand.
            outputs:
                Tableau:
                    abbr: TWBX
                    description: Pretty cool looking dashboards to describe the data.
                Combined Memo:
                    abbr: 1200E
                    description: This memo will populate for you.
                Procedures Memo:
                    abbr: PROC
                    description: This memo will populate for you.
                Controls Over Audit Tools Memo:
                    abbr: 22852
                    description: This memo will populate for you.
            inputs:
                Data Request Form:
                    abbr: DRF
                    description: Provide client-level data and field mapping.
                Dataset 2:
                    abbr: D2
                    description: Census level demographic data from prior period.
                Dataset 3:
                    abbr: D3
                    description: Census level demographic data from current period.
