Scoping:
  abbr: 1200A
  description: Something goes here for 1200A
  
Summary:
  abbr: 1200B
  description: Something goes here for 1200B
  
Combined Scoping and Summary:
  abbr: 1200E
  description: Something goes here for 1200E
  
Procedures:
  abbr: PROC
  description: Detailed logging of procedures performed to complete analytic.
  
Controls Over Audit Tools:
  abbr: 22852
  description: Description of tools used to complete analytic.
