Scoping Memo:
  name: 1200A
  description: Something goes here for 1200A
  
Summary Memo:
  name: 1200B
  description: Something goes here for 1200B
  
Combined Scoping and Summary Memo:
  name: 1200E
  description: Something goes here for 1200E
  
Procedures Memo:
  name: PROC
  description: Detailed logging of procedures performed to complete analytic.
  
Controls Over Audit Tools Memo:
  name: 22852
  description: Description of tools used to complete analytic.
